### ISSUE TITLE
您好 关于数据库中间件的疑问

### ISSUE THREAD

**Issue by lulululuding** [wanghongfei/springboot-starter-nettyweb#1]
您好，偶然间看到您的项目，仔细阅读您的项目作为初学者受益良多。但是有个疑问，您的项目里已经初具雏形，文档也很详细，但是唯独没提数据库连接。您个人倾向于什么呢? 是使用传统的JDBC，还是R2DBC, 还是再引入vertx , 希望得到您的解答，谢谢。

**Comment by wanghongfei** [comment]
你好，数据库访问如果不是特别性能敏感型应用，个人认为没有必要上全异步操作，因为会徒增复杂度，业务上的收益几乎是0。技术是业务驱动的，除非异步话能给业务带来xx万收益，节省xx万元机器费用，否则真的不值得。

不考虑异步的话随便什么mybatis之类的orm框架都行，JDBC都没问题
